version: '3.8'

services:
  tunnel:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    # Security: The token is loaded from the environment variable.
    # Never hardcode the token in this file!
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}