version: '3.8'

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - /mnt/external_drive/immich:/usr/src/app/upload # External SSD Bind Mount
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri # Intel QuickSync
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - DB_HOSTNAME=${DB_HOSTNAME}
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - immich_model_cache:/cache
    devices:
      - /dev/dri:/dev/dri # OpenVINO acceleration
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - immich_postgres:/var/lib/postgresql/data
    restart: always

volumes:
  immich_postgres:
  immich_model_cache:
  immich_redis: